sonar.projectKey=Cap-go_capacitor-nativegeocoder
sonar.organization=cap-go
sonar.sources=src,android/src/main,ios/Sources
sonar.exclusions=scripts/**,.github/**
sonar.cpd.exclusions=scripts/**
sonar.securityHotspots.exclusions=scripts/**
